version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: projectify
      POSTGRES_PASSWORD: projectify_dev
      POSTGRES_DB: projectify_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 